apiVersion: v1
kind: Secret
metadata:
  name: jawn-auth-api-secrets
data:
  jwtSecret: {{ .Values.jwtSecret }}
  sessionSecret: {{ .Values.sessionSecret }}
  testPassword: {{ .Values.testPassword }}
  jasonPassword: {{ .Values.jasonPassword }}
