apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: AuthService
      name: authentication
      auth_service: "{{ .Values.name }}:{{ .Values.port }}"
      path_prefix:  "/session/authn"
      proto: http
      allow_request_body: true
      allowed_request_headers:
        - "CSRF-Token"
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  auth_mapping
      prefix: /auth/api/
      service: {{ .Values.name }}:{{ .Values.port }}
      bypass_auth: true
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.port }}
    name: http
  selector:
    app: {{ .Values.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: '8'
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}:{{ .Values.version }}
        env:
          - name: 'PORT'
            value: '{{ .Values.port }}'
          - name: 'LOGIN_PATH'
            value: '/auth/login'
          - name: 'JWT_SECRET'
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: jwtSecret
          - name: 'SESSION_SECRET'
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: sessionSecret
        ports:
        - containerPort: {{ .Values.port }}
        readinessProbe:
          httpGet:
             path: /health
             port: {{ .Values.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
