name: CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Install docker-compose
      run: sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
    - name: Start docker-compose
      run: docker-compose up -d
    - name: wait this is dumb
      run: sleep 10s
    - name: check running containers
      run: docker ps
    - name: Run tests
      run: docker exec jawn-auth-api-test npm run test
